language: java
branches:
  only:
  - master
  - develop
notifications:
  email:
  - yu4cheem@techno.ms
cache:
  directories:
  - $HOME/.m2
before_install:
- openssl aes-256-cbc -K $encrypted_ff27d10c40ce_key -iv $encrypted_ff27d10c40ce_iv
  -in deploy/grokconstructor-default.json.enc -out deploy/grokconstructor-default.json -d
script:
  - mvn clean install appengine:update
